<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
    <title>Document</title>
</head>
<body>
    <form action="" class="container">
           <div class="" style="float:right">
                <div class="imgmove">
                    <img src="auth.png" alt="" id="resize">
                    <h3>Login</h3>
                </div>
                    <div class="mb-3">
                    <input type="email" class="col-lg-6" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Username">
                </div>
                <div class="mb-3">
                    <input type="password" class="col-lg-6" id="exampleInputPassword1" placeholder="Password" >
                </div> 
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary" id="buttonstyle">Sign in</button> 
                </div> 
           </div>
    </form>
    
</body>
</html>